version: "3"
# Creates MariaDB container and phpMyAdmin service to manage it
services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    restart: unless-stopped
    networks:
      - mysql
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: awaed
      MYSQL_USER: shaband
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql

    volumes:
      # Will use db volume and inside to path /var/lib/mysql
      - ./db/data:/var/lib/mysql

  phpmyadmin:
    # Depends on only works within same stack, but not between remote containers (even on user-defined network)
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - mysql
    container_name: phpmyadmin
    hostname: phpmyadmin
    ports:
      # Exposes external port 7000 mapped to internal of 80
      # Database required no external port of its own
      - 7000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
      # Variable to increase upload limit for importing sql db files
      UPLOAD_LIMIT: 200000K

volumes:
  # Creates persistent storage volume for database
  # Specify name so it does not append stack name in front
  db:
    name: db
networks:
  # This will create a user-defined network with name of mysql
  # Specify name so that it does not append stack name and become db_mysql
  mysql:
    name: mysql
